#! /bin/bash
. $ABBS/env/base.sh

rm -f /var/abbs/test/playground/etb/foobuild/*

$ABBS/abbs-build-mini etb/foobuild 2>$TESTLOG 1>&2
[ -e /var/abbs/test/playground/etb/foobuild/a ] || { echo FAILED : abbs-build-mini ; exit 1 
}
[ -e /var/abbs/test/playground/etb/foobuild/b ] || { echo FAILED : abbs-build-mini ; exit 1 
}
echo OK : abbs-build-mini
