#! /bin/bash
. $ABBS/env/base.sh

#TEST : bool
for i in yes Y true T 1
do
bool $i && echo OK : bool $i || echo FAILED : bool $i
done

#TEST : ablog
pushd /tmp >/dev/null
rm -f ablog
echo TESTING INFO : ablog | ablog 
grep "TESTING" ablog >/dev/null 1>&2 && echo OK : ablog || echo FAILED : ablog
popd >/dev/null

#TEST : abcommaprint
printf "TESTING INFO : "
abcommaprint a b c | grep "a \\, b \\, c" >/dev/null 1>&2 && echo OK : abcommaprint || echo FAILED : abcommaprint
