#! /bin/bash
if [ -z ${ABBS} ]; then
	if [ -f /etc/abbs/prefix ]; then
		export ABBS=$(cat /etc/abbs/prefix)
	else
		export ABBS=${PWD}
	fi
fi

. $ABBS/env/base.sh

for i in ${@}
do
	case "$i" in
		groups\/* )
			L+=" $(<"$ABBS/repo/$i")"
			;;
		*\/* )
			L+=" $i"
			;;
# FIXME: wrong IFS handling.
#		* )
#			candidate=( "$ABBS/repo/"*/"$i" )
#			[ "$candidate" != "$ABBS/repo/*/$i" ] || abdie "No vaild candidate for $i found."
#			# Now fetch the last two layers of $candidate (=candidate[0])
#			IFS=/ p=($candidate)
#			L+=" ${p[-2]}/${p[-1]}"
#			;;
	esac
done

# Now that we have found all the packages, go.

#for i in ${L}; do
#	abbs-process $i
#done

for i in $(abbsgenall "$@")
do
        abbs-process $i
done
