#! /bin/bash
if [ -z ${ABBS} ]; then
	if [ -f /etc/abbs/prefix ]; then
		export ABBS=$(cat /etc/abbs/prefix)
	else
		export ABBS=${PWD}
	fi
fi
L=()
. $ABBS/env/base.sh

type _abbs_build_procfail_handle 2>/dev/null ||
	_abbs_build_procfail_handle(){ exit; }

for i
do
	case "$i" in
		groups\/* )
			L+="$(<"$ABBS/repo/$i")"
			;;
		*\/* )
			L+=("$i")
			;;
		*)
			candidate=( "$ABBS/repo/"*/"$i" )
			[ "$candidate" != "$ABBS/repo/*/$i" ] || abdie "No vaild candidate for $i found."
			# Now fetch the last two layers of $candidate (=candidate[0])
			IFS=/ p=($candidate)
			IFS= L+="${p[-2]}/${p[-1]}"
			;;
	esac
done

# Now that we have found all the packages, go.

for i in ${L[@]}
do
	abbsgenall "$i"
        abbs-process "$i" || _abbs_build_procfail_handle
done
