#! /bin/bash
export TESTLOG="/var/log/abbs-test.log"
[ -e /tmp/abbs-test ] && rm -rf /tmp/abbs-test
mkdir -p /var/lib/abbs/build
mkdir /tmp/abbs-test
cp -r ../* /tmp/abbs-test
mv /tmp/abbs-test/unit-test/test-spec /tmp/abbs-test/repo
if [ -e /etc/abbs/prefix ]
then
mv /etc/abbs/prefix /etc/abbs/real-prefix
echo "/tmp/abbs-test" > /etc/abbs/prefix
fi

export ABBS=/tmp/abbs-test

if [ "x$1" = "x" ]
then
for i in /tmp/abbs-test/unit-test/tests/*
do
$i
done
else
/tmp/abbs-test/unit-test/tests/*-$1
fi
if [ -e /etc/abbs/real-prefix ]
then
rm /etc/abbs/prefix
mv /etc/abbs/real-prefix /etc/abbs/prefix
fi
