#!/bin/bash
# A simple function adapted from Arch Linux's makepkg scriptlet, function `extract_file'.
#
#   makepkg - make packages compatible for use with pacman
#   @configure_input@
#
#   Copyright (c) 2006-2015 Pacman Development Team <pacman-dev@archlinux.org>
#   Copyright (c) 2002-2006 by Judd Vinet <jvinet@zeroflux.org>
#   Copyright (c) 2005 by Aurelien Foret <orelien@chez.com>
#   Copyright (c) 2006 by Miklos Vajna <vmiklos@frugalware.org>
#   Copyright (c) 2005 by Christian Hamar <krics@linuxforum.hu>
#   Copyright (c) 2006 by Alex Smith <alex@alex-smith.me.uk>
#   Copyright (c) 2006 by Andras Voroskoi <voroskoi@frugalware.org>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#   Adapted by Jeff Bai, copyleft 2015 for all modifications upon the original script.

. $ABBS/env/base.sh

file=$1

# Probing file MIME/stream type.
file_type=$(file -bizL "$file")
ext=${file##*.}
cmd=''

# Deciding on program to use.
case "$file_type" in
    *application/x-tar*|*application/zip*|*application/x-zip*|*application/x-cpio*)
        cmd="bsdtar" ;;
    *application/x-gzip*)
        case "$ext" in
            gz|z|Z) cmd="gzip" ;;
            *) return;;
        esac ;;
    *application/x-bzip*)
        case "$ext" in
            bz2|bz) cmd="bzip2" ;;
            *) return;;
        esac ;;
    *application/x-xz*)
        case "$ext" in
            xz) cmd="xz" ;;
            *) return;;
        esac ;;
    *)
        if bsdtar -tf "$file" -q '*' &>/dev/null; then
            cmd="bsdtar"
        else
            return 0
        fi ;;
esac

# Actual work.
ret=0
abinfo "Extracting `echo $file` with `echo $cmd`..."
if [[ $cmd = "bsdtar" ]]; then
    $cmd -xf "$file" || ret=$?
else
    rm -f -- "${file%.*}"
    $cmd -dcf "$file" > "${file%.*}" || ret=$?
fi

if (( ret )); then
    aberr "Extraction failed... Now aborting."
    abdie
    exit 1
fi
