#! /bin/bash
. $ABBS/env/base.sh
abbscheckspec $1
for i in $ABBS/repo/$1/*
do
	[ ! -d "$i" ] && continue
	. $i/defines
	RESOLV+=" $(echo $PKGDEP $BUILDDEP) "
done
RES="$(for i in ${RESOLV}; do echo $i; done | sort -u)"

echo $RES
