#! /bin/bash
. $ABBS/env/base.sh
abbscheckspec $1
for i in $ABBS/repo/$1/*
do
	[ ! -d "$i" ] && continue
	. $i/defines
	NAMECACHE+=($(echo $PKGNAME))
	RESOLV+=" ${PKGDEP} ${BUILDDEP} "
done
for i in "${NAMECACHE[@]}"; do
	abinfo "Omitting in-tree dependency $i ..."
	RESOLV="${RESOLV//$i }"
done
RES="$(for i in ${RESOLV}; do echo $i; done | sort -u)"
echo "${RES}"
