#! /bin/bash
. $ABBS/env/base.sh
abbscheckspec $1

abrequire pm arch

if [ "$CROSS" ]; then
	pm_chroot /var/ab/cross-root/$CROSS
fi

add_if_not_exist(){
	grep "^$2\$" $1 2>/dev/null 1>&2 || echo $2 >> $1
}

TMPF="`abbstmpf`"
for i in $1
do
	DEP="`abbscalcdep $1`"
	for j in $DEP
	do
		if pm_exists $j
		then
			continue
		fi
		if pm_repoinstall $DEP >/dev/tty </dev/tty
		then
			continue
		fi
		SOURCE="`abbsfindsource $j`"
		if [ "x$SOURCE" = "x" ]
		then
			if [ "x$2" = "xr" ]
			then
				echo "Cannot find the specification for package $j"
				exit 1
			fi
			abdie "Cannot find the specification for package $j"
		fi
		SUBLIST="`abbsgenlist $SOURCE r`"
		if echo $SUBLIST | grep "^Cannot find the" >/dev/null 2>&1
		then
			if [ "x$2" = "xr" ]
			then
				echo "$SUBLIST"
				exit 1
			fi
			abdie "Sub abbsgenlist returned non-zero. Error infomation: $SUBLIST"
		fi
		for k in $SUBLIST
		do
			add_if_not_exist $TMPF $k
		done
	done
	add_if_not_exist $TMPF $1
done
LIST="`cat $TMPF`"
rm -f $TMPF
echo $LIST
