#! /bin/bash
. $ABBS/env/base.sh
abbscheckspec $1
for i in $ABBS/repo/$1/*
do
	[ ! -d "$i" ] && continue
	. $i/defines
	. $i/defines
	[[ grep "$PKGNAME" <<< "$PKGDEP" || grep "$PKGNAME" <<< "$BUILDDEP" ]] && \
	abinfo "Omitting in-tree sub-package dependency..."
	RESOLV+=" $(echo ${PKGDEP/$PKGNAME/} ${BUILDDEP/$PKGNAME/}) "
done
RES="$(for i in ${RESOLV}; do echo $i; done | sort -u)"

echo $RES
